### ISSUE TITLE
Unhelpful Error Message - TECHNOLOGY needs to set TECHNOLOGY_CCS_LIBERTY_FILES or TECHNOLOGY_NLDM_LIBERTY_FILES.

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/plsi#14]
`TECHNOLOGY needs to set TECHNOLOGY_CCS_LIBERTY_FILES or TECHNOLOGY_NLDM_LIBERTY_FILES.`

Solution: rm -rf obj/technology/saed32/

This was caused by updating plsi without cleaning anything up

**Comment by palmer-dabbelt** [comment]
This should be fixed now, it just bails out later: https://github.com/ucb-bar/plsi/commit/6a3f3c1bc2c92edc317ff35bcc79cec45d3a3836 .  The error was spurious, the new technology file has these defined correctly, but make processes top-level $(error)s before it re-builds included .mk files.
