### ISSUE TITLE
*.syn_config.json -> *.plsi_config.json in src/addons/synthesis/genus/tools/run-synthesis

### ISSUE THREAD

**Issue by cirosantilli** [ucb-bar/plsi#19]
https://github.com/ucb-bar/plsi/blob/20f371c2c4e8607aaa4365a39f3119f41d7cd7e9/src/addons/synthesis/genus/tools/run-synthesis#L21

And shouldn't it be `scenario` on those json (currently `scenerio`)?

**Comment by palmer-dabbelt** [comment]
That should be "*.plsi_config.json", I changed the name and forgot about it.

You're right, I'm just bad at spelling.

If you PR these I'll accept the patches.
